build with hugo and upload as artifact

diff --git a/.github/workflows/full-build.yml b/.github/workflows/full-build.yml
--- a/.github/workflows/full-build.yml
+++ b/.github/workflows/full-build.yml
@@ -13,20 +13,52 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
 
+
       - name: Install dependencies
         uses: borales/actions-yarn@v5.0.0
         with:
           cmd: install
 
-      - name: Build website
+
+      - name: Build with yarn
         uses: borales/actions-yarn@v5.0.0
         with:
           cmd: build
+
+
+      - name: Setup Hugo
+        uses: peaceiris/actions-hugo@v3
+        with:
+          hugo-version: '0.139.0'
+          extended: true
+
+
+      - name: Build website
+        run: hugo
+
+
+      - name: Archive website content
+        run: |
+          tar -czf website.tar.gz -C mycore.org/public .
+          if [ $? -eq 0 ]; then
+            echo "Compression succeeded."
+          else
+            echo "Compression failed."
+            exit 1
+          fi
+          
+
+      - name: Upload website content
+        uses: actions/upload-artifact@v4
+        with:
+          name: website
+          path: website.tar.gz
 
 
